[package]
name = "Orbits"
version = "0.1.0"
authors = ["eggmund <joshuacolclough2@googlemail.com>"]
edition = "2018"

[dependencies]
ggez = "0.5.0-rc.2"
specs = "0.15.0"
specs-derive = "0.4.0"
euclid = "0.20.0"