[package]
name = "Orbits"
version = "0.1.0"
authors = ["eggmund <joshuacolclough2@googlemail.com>"]
edition = "2018"

[dependencies]
ggez = "0.5.0-rc.2"
rand = "0.7.0"
serde = { version = "1.0.94", features = ["derive"] }
bincode = "1.1.4"