[package]
name = "Planets"
version = "0.1.0"
authors = ["eggmund <joshuacolclough2@googlemail.com>"]
edition = "2018"

[dependencies]
nannou = "0.9.0"
nalgebra = "0.18.0"
rand = "0.7.0"
specs = "0.15.0"